[[redirects]]
  from = "/u/:user"
  to = "/:user"
  status = 301
  force = true

[[redirects]]
  from = "/FAQ"
  to = "/FAQ/"
  status = 200

[[redirects]]
  from = "/nota"
  to = "/nota/"
  status = 200

[[redirects]]
  from = "/registro"
  to = "/registro/"
  status = 200

[[redirects]]
  from = "/directorio"
  to = "/directorio/"
  status = 200

[[redirects]]
  from = "/:user"
  to = "/u/:user/"
  status = 200